# Exclude a variety of commonly ignored directories.
extend-exclude = [
  "venv",
  "docs/conf.py",
]
# Same as Black.
line-length = 99

# Assume Python 3.8.
target-version = "py38"

# Enable using ruff with notebooks
extend-include = [ "*.ipynb" ]

[lint]
select = [ "ALL" ]

ignore = [
  "D202",
  "D213",
  "D203",
  "ISC002",
  "RUF001",
  "RUF002",
  "RUF003",
  "B008",
  "S101",   # Use of `assert` detected
  "COM812", # Trailing comma missing
  # Covered by formatter
  "ISC001",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/*" = [
  "ARG001",
  "ANN201", # Missing return type annotation for public function
]

[lint.isort]
required-imports = [ "from __future__ import annotations" ]
known-first-party = [ "odiff_py" ]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"
